### ISSUE TITLE
合同信息管理

### ISSUE THREAD

**Issue by talkactive** [gesoftss/xyl#16]
缴纳日期缺少文字

车辆运费输入框是金额

![image](https://user-images.githubusercontent.com/8265919/35481424-4b5e8e58-045e-11e8-8e1a-7cefbab51725.png)
交财务日期 ：日期下拉框不能全显示

![image](https://user-images.githubusercontent.com/8265919/35481429-687e8808-045e-11e8-906d-f290ba4e7fec.png)
签订部门下拉框：太长
@gesofts

**Comment by gesofts** [comment]
@talkactive 改好
