### ISSUE TITLE
船舶人员管理，需要控制一条船只能有一个船长

### ISSUE THREAD

**Issue by talkactive** [gesoftss/xyl#33]
@wangzhifang123 
船舶人员管理，需要控制一条船只能有一个船长

姓名是可以重复的，添加的时候不应该提示重复
![image](https://user-images.githubusercontent.com/8265919/35497880-ff3e1aa8-0506-11e8-8466-e1382fbd3036.png)
查询界面年龄没显示

**Comment by wangzhifang123** [comment]
一个船号只能有一个船长
