### ISSUE TITLE
 运价信息管理：客户信息、运价信息是可以重复的；查询界面增加创建人，创建时间

### ISSUE THREAD

**Issue by talkactive** [gesoftss/xyl#39]
![image](https://user-images.githubusercontent.com/8265919/35511599-7b22e0c4-0537-11e8-808b-dfa14d94b47a.png)
@gesofts @wangzhifang123 运价信息管理：客户信息、运价信息是可以重复的；查询界面增加创建人，创建时间

**Comment by gesofts** [comment]
@talkactive  已修改
