### ISSUE TITLE
运力调度，船舶类型显示有问题

### ISSUE THREAD

**Issue by talkactive** [gesoftss/xyl#51]
![image](https://user-images.githubusercontent.com/8265919/35516082-cd2ae8b8-0545-11e8-9f60-2dc8f2798905.png)
@jjaaddiicc @TeamMicLee

**Comment by TeamMicLee** [comment]
现在这边是后台给我返回类型名称字段还是前台进行转换？

**Comment by jjaaddiicc** [comment]
@TeamMicLee 前端固定转换  根据shipFlag  1：自有船舶  2：挂靠船舶  3：临调船
