### ISSUE TITLE
客户任务下单，卸货时间需大于等于装货时间

### ISSUE THREAD

**Issue by talkactive** [gesoftss/xyl#64]
选择流向信息时，自动带出航行区域，
装货途径如果选择场地，则大轮相关信息可以为空（大轮批次，大轮总载量，大轮到达位置，大轮预计到达时间，大轮预计离开时间）；
状态的布局有问题；同时默认状态是启用；
船户参考运价：所有的参考运价都应该先取运价信息里的，如果取不到就取合同里的；
客户任务下单首次新增流向的时候提示数据重复，此问题是阻塞问题，直接影响主流程了
流向的总吨位之后必须小于任务的总吨位

**Comment by gesofts** [comment]
@talkactive 已修改
